// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    Chart1: typeof import('./components/dashboard/chart1.vue')['default']
    Chart2: typeof import('./components/dashboard/chart2.vue')['default']
    Dashboard: typeof import('./components/dashboard/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LEcharts: typeof import('./components/l-echarts/index.vue')['default']
    LEchartsLine1: typeof import('./components/l-echarts-line-1/index.vue')['default']
    LEchartsLine2: typeof import('./components/l-echarts-line-2/index.vue')['default']
    LEchartsPie1: typeof import('./components/l-echarts-pie-1/index.vue')['default']
    LEchartsPie2: typeof import('./components/l-echarts-pie-2/index.vue')['default']
    LIfyIcon: typeof import('./components/l-ify-icon/index.vue')['default']
    LTableEdit: typeof import('./components/l-table-edit/index.vue')['default']
    LUploadFile: typeof import('./components/l-upload-file/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
